export const FEED_WS_CONNECTION_START = 'FEED_WS_CONNECTION_START';
export const FEED_WS_CONNECTION_STOP = 'FEED_WS_CONNECTION_STOP';

export const PROFILE_ORDERS_WS_CONNECTION_START = 'PROFILE_ORDERS_WS_CONNECTION_START';
export const PROFILE_ORDERS_WS_CONNECTION_STOP = 'PROFILE_ORDERS_WS_CONNECTION_STOP';